[package]
name = "walletcursive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "*"
serde = { version = "*", features = ["derive"] }
serde_derive = "*"
serde_yaml = "*"
